modified:   bootstrap
modified:   bootstrap.d/cargo.sh

modified:   bootstrap.d/cargo/eza.sh

modified:   bootstrap.d/cargo/lolcrab.sh

modified:   bootstrap.d/git-hooks.sh

modified:   bootstrap.d/kitty/dracula.sh

modified:   bootstrap.d/nvim/lazy.sh

new file:   bootstrap.d/python.sh

modified:   bootstrap.d/zsh/oh-my-zsh.sh

modified:   bootstrap.d/zsh/zshrc.sh

modified:   hooks/prepare-commit-msg.sh

modified:   util.sh

modified:   ../zsh/source/after/docker.zsh

modified:   ../zsh/source/after/eza.zsh

modified:   ../zsh/source/after/nvim.zsh

modified:   ../zsh/source/before/plugins.zsh

modified:   ../zsh/zshrc.zsh

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -8,10 +8,10 @@
 set -eu
 
 for cmd in curl git; do
-    if ! command -v $cmd >/dev/null 2>&1; then
-        echo "Error: \`$cmd\` not found. Please install it, then run \`yadm bootstrap\` again." >&2
-        exit 1
-    fi
+        if ! command -v $cmd >/dev/null 2>&1; then
+                echo "Error: \`$cmd\` not found. Please install it, then run \`yadm bootstrap\` again." >&2
+                exit 1
+        fi
 done
 
 # Directory to look for bootstrap executables in
@@ -20,20 +20,20 @@ export YADM_DIR="$(dirname $BOOTSTRAP_D)"
 export UTIL="$YADM_DIR/util.sh"
 
 if ! [ -d "$BOOTSTRAP_D" ]; then
-    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
-    exit 1
+        echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+        exit 1
 fi
 
 . "$(dirname $BOOTSTRAP_D)/util.sh"
 
 find -L "$BOOTSTRAP_D" -type f -iname "*.sh" | sort | while IFS= read -r bootstrap; do
-    if [ -x "$bootstrap" ]; then
+if [ -x "$bootstrap" ]; then
         if ! "$bootstrap"; then
-            echo "Error: bootstrap '$bootstrap' failed" >&2
-            exit 1
+                echo "Error: bootstrap '$bootstrap' failed" >&2
+                exit 1
         fi
-    else
+else
         echo "Skipping non-executable '.sh' file \`$bootstrap\`" >&2
         exit 1
-    fi
+fi
 done
